apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql

  labels:
    app: mysql

  namespace: expense  

spec:  
  replicas: 1
  selectors:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        environment: dev
        project: expense
        app: mysql  

  spec:
    containers:
    - name: mysql
      image: pushpa4/mysql:1.0.2


# Here we are creating the expense project in single namespace, so mysql-backend communication purpose use service


apiVersion: v1
kind: Service

metadata: 
  name: mysql
  namespace: expense


spec:
  type: ClusterIP

  selector:
    app: mysql
    project: expense
    environment: dev

  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306   

